-- My Algartempo — estrutura do portal do colaborador
-- Executar no Supabase SQL Editor.

create table if not exists public.employee_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text,
  phone text,
  address text,
  nif text,
  social_security_number text,
  iban text,
  emergency_contact_name text,
  emergency_contact_phone text,
  polo text,
  role text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.employee_placements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  company_name text not null,
  job_title text,
  polo text,
  workplace text,
  start_date date,
  end_date date,
  contract_type text,
  contact_name text,
  contact_phone text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.employee_shifts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  shift_date date not null,
  start_time time,
  end_time time,
  break_minutes integer not null default 0,
  company_name text,
  workplace text,
  status text not null default 'scheduled',
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.employee_hours (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  work_date date not null,
  clock_in timestamptz,
  clock_out timestamptz,
  total_minutes integer not null default 0,
  overtime_minutes integer not null default 0,
  status text not null default 'confirmed',
  created_at timestamptz not null default now()
);

create table if not exists public.employee_documents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  category text not null default 'other',
  file_url text not null,
  file_name text,
  requires_signature boolean not null default false,
  signed_at timestamptz,
  status text not null default 'available',
  created_at timestamptz not null default now()
);

create table if not exists public.employee_leave_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  days numeric(6,2) not null default 0,
  reason text,
  status text not null default 'pending',
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.employee_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null,
  category text not null default 'other',
  message text not null,
  status text not null default 'open',
  admin_reply text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.employee_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  message text,
  type text not null default 'info',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists employee_shifts_user_date_idx on public.employee_shifts(user_id, shift_date);
create index if not exists employee_hours_user_date_idx on public.employee_hours(user_id, work_date);
create index if not exists employee_documents_user_idx on public.employee_documents(user_id);
create index if not exists employee_requests_user_idx on public.employee_requests(user_id, created_at desc);
create index if not exists employee_notifications_user_idx on public.employee_notifications(user_id, created_at desc);

alter table public.employee_profiles enable row level security;
alter table public.employee_placements enable row level security;
alter table public.employee_shifts enable row level security;
alter table public.employee_hours enable row level security;
alter table public.employee_documents enable row level security;
alter table public.employee_leave_requests enable row level security;
alter table public.employee_requests enable row level security;
alter table public.employee_notifications enable row level security;

-- Helpers
create or replace function public.is_admin_user()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.admin_users where id = auth.uid()); $$;

-- Remove/recreate portal policies safely

do $$ declare r record; begin
  for r in select policyname, tablename from pg_policies where schemaname='public' and tablename in (
    'employee_profiles','employee_placements','employee_shifts','employee_hours','employee_documents',
    'employee_leave_requests','employee_requests','employee_notifications') loop
    execute format('drop policy if exists %I on public.%I', r.policyname, r.tablename);
  end loop;
end $$;

create policy employee_profiles_self_select on public.employee_profiles for select to authenticated using (user_id=auth.uid() or public.is_admin_user());
create policy employee_profiles_self_insert on public.employee_profiles for insert to authenticated with check (user_id=auth.uid() or public.is_admin_user());
create policy employee_profiles_self_update on public.employee_profiles for update to authenticated using (user_id=auth.uid() or public.is_admin_user()) with check (user_id=auth.uid() or public.is_admin_user());

create policy employee_placements_self_select on public.employee_placements for select to authenticated using (user_id=auth.uid() or public.is_admin_user());
create policy employee_placements_admin_write on public.employee_placements for all to authenticated using (public.is_admin_user()) with check (public.is_admin_user());

create policy employee_shifts_self_select on public.employee_shifts for select to authenticated using (user_id=auth.uid() or public.is_admin_user());
create policy employee_shifts_admin_write on public.employee_shifts for all to authenticated using (public.is_admin_user()) with check (public.is_admin_user());

create policy employee_hours_self_select on public.employee_hours for select to authenticated using (user_id=auth.uid() or public.is_admin_user());
create policy employee_hours_admin_write on public.employee_hours for all to authenticated using (public.is_admin_user()) with check (public.is_admin_user());

create policy employee_documents_self_select on public.employee_documents for select to authenticated using (user_id=auth.uid() or public.is_admin_user());
create policy employee_documents_admin_write on public.employee_documents for all to authenticated using (public.is_admin_user()) with check (public.is_admin_user());

create policy employee_leave_self_all on public.employee_leave_requests for all to authenticated using (user_id=auth.uid() or public.is_admin_user()) with check (user_id=auth.uid() or public.is_admin_user());
create policy employee_requests_self_all on public.employee_requests for all to authenticated using (user_id=auth.uid() or public.is_admin_user()) with check (user_id=auth.uid() or public.is_admin_user());
create policy employee_notifications_self_select on public.employee_notifications for select to authenticated using (user_id=auth.uid() or public.is_admin_user());
create policy employee_notifications_self_update on public.employee_notifications for update to authenticated using (user_id=auth.uid() or public.is_admin_user()) with check (user_id=auth.uid() or public.is_admin_user());
create policy employee_notifications_admin_insert on public.employee_notifications for insert to authenticated with check (public.is_admin_user());
create policy employee_notifications_admin_delete on public.employee_notifications for delete to authenticated using (public.is_admin_user());

-- Bucket privado para documentos dos colaboradores
insert into storage.buckets (id, name, public) values ('employee-documents','employee-documents',false)
on conflict (id) do update set public=false;

drop policy if exists employee_docs_self_read on storage.objects;
drop policy if exists employee_docs_admin_all on storage.objects;
create policy employee_docs_self_read on storage.objects for select to authenticated
using (bucket_id='employee-documents' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_admin_user()));
create policy employee_docs_admin_all on storage.objects for all to authenticated
using (bucket_id='employee-documents' and public.is_admin_user())
with check (bucket_id='employee-documents' and public.is_admin_user());

-- Trigger simples para updated_at
create or replace function public.touch_employee_updated_at() returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end; $$;

drop trigger if exists employee_profiles_touch on public.employee_profiles;
create trigger employee_profiles_touch before update on public.employee_profiles for each row execute function public.touch_employee_updated_at();
drop trigger if exists employee_leave_touch on public.employee_leave_requests;
create trigger employee_leave_touch before update on public.employee_leave_requests for each row execute function public.touch_employee_updated_at();
drop trigger if exists employee_requests_touch on public.employee_requests;
create trigger employee_requests_touch before update on public.employee_requests for each row execute function public.touch_employee_updated_at();

-- Convites criados pelo Backoffice antes da ativação do acesso
create table if not exists public.employee_invites (
  id bigint generated by default as identity primary key,
  full_name text not null default '',
  email text not null,
  phone text,
  address text,
  nif text,
  social_security_number text,
  iban text,
  emergency_contact_name text,
  emergency_contact_phone text,
  polo text,
  role text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  activated_at timestamptz
);
create index if not exists employee_invites_email_idx on public.employee_invites(lower(email));
alter table public.employee_invites enable row level security;
drop policy if exists employee_invites_admin_all on public.employee_invites;
drop policy if exists employee_invites_self_select on public.employee_invites;
drop policy if exists employee_invites_self_update on public.employee_invites;
create policy employee_invites_admin_all on public.employee_invites for all to authenticated using (public.is_admin_user()) with check (public.is_admin_user());
create policy employee_invites_self_select on public.employee_invites for select to authenticated using (lower(email)=lower(coalesce(auth.jwt()->>'email','')));
create policy employee_invites_self_update on public.employee_invites for update to authenticated using (lower(email)=lower(coalesce(auth.jwt()->>'email',''))) with check (lower(email)=lower(coalesce(auth.jwt()->>'email','')));
